---
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
- name: start nginx
  service:
      name: nginx
      state: started

- name: copy the nginx config file
  copy:
    src: nginx_password_config.cfg
    dest: /etc/nginx/sites-available/password_proxy.cfg
  become: yes
- name: create symlink
  file:
    src: /etc/nginx/sites-available/password_proxy.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes

- name: Make sure we can use htpasswd module
  apt: 
    pkg: python3-passlib
    state: present

- name: Create .htpasswd file
  community.general.htpasswd:
    path: /etc/nginx/htpasswd
    name: admin
    password: '{{ kb_admin_password }}'
    owner: root
    group: www-data
    mode: '0640'

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes